version: '3'

services:
  app:
    build:
      context: .
      dockerfile: qro2408/mkoong
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_MYSQL_HOST=mysql
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USERNAME=root
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - DB_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    volumes:
      - .:/usr/src/app

  mysql:
    image: mysql:8.0
    ports:
      - ${DB_MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command:
      - --connect-timeout=31536000
      - --net_write_timeout=600
      - --max_allowed_packet=16M
      - --collation-server=utf8mb4_general_ci
      - --default-time-zone=${DB_MYSQL_TIMEZONE}
      - --character-set-server=${DB_MYSQL_CHARSET}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  redis_data:
