export enum MBTI {
  ENTP = 'ENTP',
  ENFP = 'ENFP',
  ESTP = 'ESTP',
  ESTJ = 'ESTJ',
  ENFJ = 'ENFJ',
  ESFP = 'ESFP',
  ENTJ = 'ENTJ',
  ESFJ = 'ESFJ',
  INTP = 'INTP',
  INFP = 'INFP',
  ISTP = 'ISTP',
  ISTJ = 'ISTJ',
  INFJ = 'INFJ',
  ISFP = 'ISFP',
  ISFJ = 'ISFJ',
  INTJ = 'INTJ',
}
