name: Node.js CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t qro2408/mkoong:latest .

      # latest 태그도 푸시
      - name: Docker push (latest)
        run: docker push qro2408/mkoong:latest

      - name: Set workflow ID
        run: echo "workflow_id=${{ github.run_id }}" >> $GITHUB_ENV
