name: release app

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Generate deployment package
        run: zip -r ${{ github.sha }}.zip . -x "*.git*" node_modules/*

      # 도커 허브에 로그인하기
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Generate unique version label
      #   id: generate_version
      #   run: echo "version=$(date +'%Y%m%d%H%M%S')-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mkoong
          environment_name: Mkoong-env
          version_label: ${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          region: ap-northeast-2
          deployment_package: ${{ github.sha }}.zip
          wait_for_environment_recovery: 200

      # - name: Update EB environment
      #   run: |
      #     eb deploy --label ${{ github.sha }}

      # - name: Deploy using Docker Compose
      #   run: docker-compose -f docker-compose.yml up -d
      #   env:
      #     GITHUB_SHA: ${{ github.sha }} # GITHUB_SHA를 환경 변수로 전달
