name: deploy app

on:
  workflow_run:
    workflows: ['Node.js CI']
    types:
      - completed

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Genrate Deployment Package
        run: zip -r ${{ github.sha }}.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mkoong
          environment_name: Mkoong-node
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          deployment_package: ${{ github.sha }}.zip

  # 우선은 노드로 배포 진행하기 위해 잠시 주석
  # deploy:
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         cache: 'yarn'

  #     - name: Generate deployment package
  #       run: zip -r ${{ github.sha }}.zip . -x "*.git*" node_modules/*

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Deploy to EB
  #       uses: einaregilsson/beanstalk-deploy@v21
  #       with:
  #         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         application_name: mkoong
  #         environment_name: Mkoong-env-1
  #         version_label: ${{ github.sha }}
  #         version_description: ${{ github.event.head_commit.message }}
  #         region: ap-northeast-2
  #         deployment_package: ${{ github.sha }}.zip
  #         # deployment_package : docker-compose.yml
  #         wait_for_environment_recovery: 200
