name: release app

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Generate deployment package
        run: zip -r ${{ github.sha }}.zip . -x "*.git*" node_modules

      - name: Generate unique version label
        id: generate_version
        run: echo "version=$(date +'%Y%m%d%H%M%S')-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mkoong
          environment_name: Mkoong-env-4
          version_label: ${{ steps.generate_version.outputs.version }}
          version_description: ${{ github.event.head_commit.message }}
          region: ap-northeast-2
          deployment_package: ${{ github.sha }}.zip
          wait_for_environment_recovery: 200

      - name: Update EB environment
        run: |
          eb deploy --label ${{ steps.generate_version.outputs.version }}
